name: odoo_dte_srl
description: "Cliente android nativo para Odoo Enterprise/Community"
publish_to: 'none'
version: 1.0.3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.10
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.35.2
  zebrautil: ^1.4.42
  flutter_launcher_icons: ^0.14.3
  app_settings: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path_android: "assets/icon.png" 
  android: true
  min_sdk_android: 21
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
